version: 2.0.0.{build}
skip_tags: true
image: Visual Studio 2022
configuration: Release
build_script:
  - dotnet restore ./route4me-csharp-sdk/Route4MeSDK.sln
  - dotnet build ./route4me-csharp-sdk/Route4MeSDK.sln /p:Configuration=Release /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-pre /p:Version=%APPVEYOR_BUILD_VERSION% /verbosity:minimal
  - dotnet pack ./route4me-csharp-sdk/Route4MeSDKLibrary/Route4MeSDKLibrary.csproj -c Release --no-build /p:PackageVersion=%APPVEYOR_BUILD_VERSION%-pre /p:Version=%APPVEYOR_BUILD_VERSION%
test_script:
  - dotnet test --configuration Release --no-build ./route4me-csharp-sdk/Route4MeSDKUnitTest/Route4MeSDKUnitTest.csproj

artifacts:
  - path: '**\*.nupkg'